database:
    type: postgres
    database: infect
    schema: infect_sample_storage
    hosts:
        - host: ${SAMPLE_STORAGE_SERVICE_DB_HOST}
          username: ${SAMPLE_STORAGE_SERVICE_DB_USER}
          password: ${SAMPLE_STORAGE_SERVICE_DB_PASSWORD}
          port: 5432
          pools:
            - read
            - write
          maxConnections: 20