database:
    type: postgres
    database: infect
    schema: infect_sample_storage
    hosts:
        - host: ${SAMPLE_STORAGE_DB_HOST}
          username: root
          password: ${SAMPLE_STORAGE_DB_PASSWORD}
          port: 5432
          pools:
            - read
            - write
          maxConnections: 20